name: Daily Prayer Times Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch new prayer times
        env:
          PRAYER_API_KEY: ${{ secrets.PRAYER_API_KEY }}
          PRAYER_API_BASE_URL: ${{ secrets.PRAYER_API_BASE_URL }}
        run: node update_prayers.mjs

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'


          git add prayers.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated update: prayers.json" && git push)
